### ISSUE TITLE
"Anonymous answers" option is displayed incorrectly after form answers have been submitted

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#14]
**Steps to reproduce:**
1. Open an active assessment event with "anonymous answers" activated option
2. Fill in any form and turn off "anonymous answers" option (deactivate)
3. Close assessment event and reopen the same form

**Actual result:**
"Anonymous answers" option is activated (turned on)

**Expected result:**
"Anonymous answers" option is deactivated (turned off)

**Req ID:** REQF_asss-004, REQF_asss-009

The comment from the previous developer:
 
_There are two possible controversial moments:
"Anonymous answers" option is hardcoded on FE side, that always display turned on mode.
After turning on “isAnonymous” option  in survey and submitting the form http://vm-a834f9ac-1c23-40f2-9461-618361703efd.premium.cs2.netpoint-dc.com:8081/#!/Assessment/getList - query returns changed “isAnonymous“ mode for any others “isAnonymous” form fileds in current project (see attached picture). It is needed to discuss with backend if it’s an expected behavior._
![strangeBehavior](https://user-images.githubusercontent.com/26703076/74496781-51e01d80-4f0e-11ea-8174-32318df62974.png)

**Comment by iperevozchikov** [comment]
@vanekbr Please, re-check bug with next input data:
1. Create assessment event with Anonymity: on, Show all forms on one page: on;
2. Start to participate;
3. Scroll down;
4. Fill in last form;
5. Turn off Anonymity;
6. Save changes;
7. Reopen assessment.

**Actual result**: Anonymity is on
**Expected result**: Anonymity is off
