### ISSUE TITLE
Selected drop-down list values are not vertically aligned

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#22]
**Steps to reproduce:**
1) Go to the "Users" section for the administrator
2) Open the filtration unit
3) Select values for the “Status” and “Role” drop-down lists

**Browser:** Safari

**Actual result:** The selected value is pressed to the top of the value output field (screen)

**Expected result:** The selected values are aligned in the middle of the vertical

**Req ID:** REQF_adm_user-005, REQF_adm_asss-003

![Incorrect vertical aligned.png](https://images.zenhubusercontent.com/58f5680351aa2c30577b8f56/e3d3b8ae-90f2-40d3-ba4f-cec6cf27039c)

**Comment by iperevozchikov** [comment]
@elenaustyugova Cannot reproduce bug by provided scenario. Selected item displaying with correct align.

OS: Ubuntu
Browsers: Firefox 73.0.1, Chromium 78.0.3904.332, 80.0.3987.87

I suggest to check again bug and update reproduction steps with additional information or decline bug.

**Comment by elenaustyugova** [comment]
@iperevozchikov please check it in Safari. It was not mentioned in the description of the bug, I updated it. It's a minor bug. If it can not be fixed, we can decline it.
