### ISSUE TITLE
The deleted project is automatically selected in the selection field when adding a project to an event

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#26]
It is expected that when you open the add project window to the event, there will always be the same behavior.

**Steps to reproduce:**
1) Go to the "Assessment Events" section
2) Create a new evetn
3) In the event settings, click on adding a project
4) Select any project
5) Click "Add projects to event"
6) Delete the added project
7) Go to add project

**Actual result:** A deleted project is selected in the project selection field (screen).

**Expected result**: The project selection field is empty.

**Req ID**: REQF_adm_asss-004

![Added remote group](https://user-images.githubusercontent.com/26703076/74498907-ac7c7800-4f14-11ea-9c44-58754e2844c9.png)

**Comment by vanekbr** [comment]
@elenaustyugova Can not reproduce the issue.
