### ISSUE TITLE
The switch "Vote anonymously" switches when the form is cleared

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#27]
The error is repeated only if during the creation/editing of the project the option "Show forms on the same page" is set to "No" (screen 1)

**Steps to reproduce:**
1) Create a new event
2) Add a project to the event with the possibility of anonymous answers and the “Show forms on the same page” option turned off
3) Go to the event after the start as a participant
4) Answer the form questions
5) Click on the "Clear" button

**Actual result:** The "Vote anonymously" switch is set to the off position (screen 2)

**Expected result:** The "Vote anonymously" switch remains in the on position

**Req ID:** REQF_asss-009

![Vote anonymously 2](https://user-images.githubusercontent.com/26703076/74498999-f8c7b800-4f14-11ea-8537-281e4f85efd9.png)
![Vote anonymously 1](https://user-images.githubusercontent.com/26703076/74499000-fa917b80-4f14-11ea-8165-f6bb1074efc1.png)

**Comment by vanekbr** [comment]
Root cause: Clear button was triggering assessment form reset. Anonymity switch was placed in <form> tag and was also clearing.
Solution: Anonymity switch made standalone.
