### ISSUE TITLE
Correct validation for the event date and time selection field

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#32]
You need to change the validation for the input fields for the date and time of the assessment event. These fields are present when creating an event and when editing an event.

**Steps to reproduce:**
1) Go to "Assessment Events"
2.1) Proceed to create a new event.
2.2) Proceed to edit the event in the "Not started" state

**1) Prohibit the ability to enter invalid characters**

**Actual result:** You can enter any characters
**Expected Result:** Limit the allowed characters to be entered as follows:
- numbers from 0 to 9
- point "."
- space " "
- colon ":"

**2) Display only 1 error for a field at a time**
The multiplicity of errors under the field is a non-informative solution. Show only the error that is most relevant for the data entered.

**Actual result:** If an error occurs, one of the fields displays 3 errors at once (screen)
**Expected result:** When displaying an error, follow the following logic:
- if there are invalid characters in the field or the data format does not match the desired one - output the error "Wrong date format"
- otherwise, if the elapsed time point is set in the field - output the error "Date cannot be in the past"
- otherwise, if the start date of the event is later than the end date - output the error "Start date cannot be after end date"
- otherwise, all is well and errors are not needed.

**Req ID:** REQF_adm_asss-001, REQF_adm_asss-006

![Снимок экрана от 2019-04-11 09-40-54.png](https://images.zenhubusercontent.com/58f5680351aa2c30577b8f56/053056e5-8765-4407-82e5-96810aa94dec)

**Comment by iperevozchikov** [comment]
@elenaustyugova @vanekbr 
Requirement: **Prohibit the ability to enter invalid characters**
Currently implemented option with activating `readonly` property on input field that represents datetime value. 
In the future when we'll have enough time, it may be enhanced with a solution that would include filtering input characters, supporting the predefined mask and resolving incorrect value with applying previous valid state.
