### ISSUE TITLE
There is no empty value validation when adding a project to an event

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#35]
**Steps to reproduce:**
1) Go to the section "Assessment events"
2) Go to event details in the status "Not started"
3) Click on the add project button
4) Click in the group selection field
5) Click outside the group selection field

Check the same case for Admin -> Groups -> Group details -> Add users to group

**Actual result:** The input field is displayed unchanged, the add button is available for pressing

**Expected result:** The input fields have a red frame, the error "Field is required"/"Поле должно быть заполнено" (EN/RU) under the input field, the add button is not available to click

**Req ID:** REQF_adm_asss-009

![Add project to event validation.png](https://images.zenhubusercontent.com/58f5680351aa2c30577b8f56/c084750d-84e4-453a-a423-3add85569d5b)

**Comment by iperevozchikov** [comment]
@vanekbr Please, re-check second option Admin -> Groups -> Group details -> Add users to group. Seems like form doesn't clean up on hidding modal window, it cause showing previous validation errors
