### ISSUE TITLE
Error when editing date/time in assessment event notification

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#36]
The bug is repeated when creating a notification and when editing an existing notification in the assessment event.

**Steps to reproduce:**
1) Go to the event details in the status "In progress" or "Not started"
2) Click on the create notification button/edit notification button
3) Close the pop-up
3) Click on the create notification button/edit notification button once again (reopen the pop-up)
4) Click on the date/time input (datepicker opens)
5) Close the date/time input

**Actual result:** 
1) 2 errors appear: "Field is required", "Date cannot be in the past"
2) Datepicker icon is inactive

**Expected result:** 
1) No errors appear
2) Datepicker icon is active 

**Req ID:** REQF_adm_asss-011, REQF_adm_asss-012

![Снимок экрана от 2019-04-11 15-00-58.png](https://images.zenhubusercontent.com/58f5680351aa2c30577b8f56/04d05faf-cfc8-4ca8-af11-06b006183608)

**Comment by iperevozchikov** [comment]
@elenaustyugova Am I correnctly understand, that we should have ability to set notification at any date and ignore current validation about "date is past"?
