### ISSUE TITLE
Check licenses used in the project (frontend part)

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#66]
### Description
We should make sure that all package licenses are OSS and no restrictions to use them. Automate the process if possible (or create a separate ticket). Create tickets to replace packages if any not OSS licenses.

### Acceptance criteria:
1. All licenses used in the project are OSS.
2. If any license is not OSS, separate tickets to replace packages are created

**Comment by vanekbr** [comment]
@MaverickW @elenaustyugova 
The following set of licenses projects dependencies are currently using:
- MIT
- Apache 2.0
- BSD-3-Clause 
- (OFL-1.1 AND MIT)
- (GPL-2.0 OR LGPL-2.1 OR MPL-1.1)

All of them are allowed to be used in OSS.
